### ISSUE TITLE
Twitter APIの使用がユーザー認証になっている

### ISSUE THREAD

**Issue by kumamono** [yume-yu/gbf_search_tool#26]
Twitter APIの使用がユーザー認証になっているため180回/15分の使用制限になっている
今ここのユーザー認証になっている
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

こっちに変える
https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only

**Comment by yume-yu** [comment]
2つ目のリンクの方法でできた
![スクリーンショット 2020-09-22 23 18 58](https://user-images.githubusercontent.com/30368684/93894741-04405480-fd2a-11ea-9125-37d3f010de90.png)

**Comment by yume-yu** [comment]
必要な変更
1. requests_oauthlib を使ったユーザー認証からConsumerKey(=API Key)とConsumerSecret(=API Secret)を使ってトークンを生成、それを使ってリクエストを投げる Application Authに変更する
    1. CK, CSからトークンを取得する関数をつくる
    1. トークンを使ったリクエストをする関数をつくる (期限切れ時にトークンの再取得をする)
1. API limitを取得できることがわかったので、リクエスト可能回数を確認し、ステータスに表示するスレッドのクラスを作成する
    cf. https://developer.twitter.com/en/docs/twitter-api/v1/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status
1. StatusMonitorクラスのレイアウトを変更し、表示する場所/更新関数をつくる

**Comment by yume-yu** [comment]
ライブラリ側での解決策を見つけた。ついでに自動更新もある

https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#backend-application-flow

**Comment by yume-yu** [comment]
b465356 にて APIのきりかえ完了
