### ISSUE TITLE
マルチバトル一覧の表示/選択画面をつくる

### ISSUE THREAD

**Issue by yume-yu** [yume-yu/gbf_search_tool#5]
## 作業対象
* view.py

### カテゴリ選択画面
1. 引数はとらない
1. カテゴリの一覧を取得する
1. カテゴリの一覧を表示する
1. カテゴリIDの入力を受け取る
1. 入力されたIDを返す

### マルチ選択画面
1. 引数はカテゴリID
1. 引数のカテゴリIDのボス一覧を取得する
1. 取得した一覧を表表示する
1. ボスIDの入力を受け付ける
1. 入力されたIDと検索クエリを返す

## やること
- [x] 表示方法を検討する
- [x] ライブラリを検討する
- [x] 実装する

**Comment by kumamono** [comment]
＃#5 cursesを使用

**Comment by yume-yu** [comment]
good work,
